#!/bin/bash
### FOR USERS WHO ALREADY KNOW START UP BASICS SUCH AS:
### partions -> file system -> mount -> pacstrap -> genfstab -> arch-chroot

### ARCH SETUP ###
printf '%s\n\n\n## STARTING ARCH ##\n\n\n'
sleep 2

## EDIT
##(1) timezone/language/localhost
##(2) root
##(3) pacman
##(4) gpu
##(5) systemctl
##(6) user

# TIMEZONE - LANGUAGE - HOST
ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
hwclock --systohc
timedatectl set-ntp true
sed -i '178s/.//' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "machine1" >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 machine1.localdomain machine1" >> /etc/hosts
# ROOT
echo root:32435 | chpasswd

# PACMAN
pacman -S grub efibootmgr mtools dosfstools base-devel linux-headers iptables-nft ipset firewalld dhclient alsa-utils pulseaudio pipewire pipewire-alsa pipewire-jack pavucontrol networkmanager nm-connection-editor network-manager-applet dialog wpa_supplicant openssh reflectori
#laptop: acpi acpi_call acpid tlp sof-firmware
#nettools: wireless-tools iwd dhcpd bluez bluez-utils

# GRUB
grub-install --target=i386-pc /dev/[DISK NAME]
grub-mkconfig -o /boot/grub/grub.cfg

# GPU
#pacman -S xf86-video-intel
#pacman -S xf86-video-amdgpu
#pacman -S nvidia nvidia-utils nvidia-settings

# SYSTEMCTL
#systemctl enable NetworkManager
#systemctl enable firewalld
#systemctl enable sshd
#systemctl enable reflector.service
#systemctl enable reflector.timer
#systemctl enable tlp
#systemctl enable acpid

# USER
useradd -g wheel -m user1
echo user1:21324 | chpasswd
sed -i '85s/..//' /etc/sudoers

### SELF DELETE ###
printf '%s\n\n\n## INSTALLATION FINISHED ##\n  ## DELETING FILE IN ##\n\n'
printf '%s\t3..'
sleep 1
printf '%s2..'
sleep 1
printf '%s1..'
sleep 1
rm bios-version
printf '%s\n\t  DONE\n'
