#!/bin/bash
### FOR USERS WHO ALREADY KNOW START UP BASICS SUCH AS:
### partions -> file system -> mount -> pacstrap -> genfstab -> arch-chroot

## EDIT HEADER CHILDREN
##(1) timezone/language/localhost
##(2) root
##(3) pacman
##(4) gpu
##(5) systemctl
##(6) user

### ARCH SETUP ###
printf '%s\n\n\n## STARTING ARCH ##\n\n\n'
sleep 2

# TIMEZONE - LANGUAGE - HOST
ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
hwclock --systohc
timedatectl set-ntp true
sed -i '178s/.//' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "machine1" >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 machine1.localdomain machine1" >> /etc/hosts
# ROOT
echo root:32435 | chpasswd

# PACMAN
pacman -S --noconfirm linux linux-firmware grub efibootmgr sof-firmware alsa-utils pulseaudio pipewire pipewire-alsa pipewire-jack networkmanager nm-connection-editor wpa_supplicant firewalld dhcpcd openssh reflector
#laptop: acpid tlp acpi acpi_call

grub-install --target=x86_64-efi  --bootloader-id=grub_uefi --recheck
grub-mkconfig -o /boot/grub/grub.cfg

# GPU
#pacman -S xf86-video-intel
#pacman -S xf86-video-amdgpu
#pacman -S nvidia nvidia-utils nvidia-settings

# SYSTEMCTL
#systemctl enable NetworkManager
#systemctl enable firewalld
#systemctl enable dhcpcd
#systemctl enable sshd
#systemctl enable reflector.service
#systemctl enable reflector.timer
#systemctl enable tlp
#systemctl enable acpid

# USER
useradd -g wheel -m user1
echo user1:21324 | chpasswd
sed -i '88s/..//' /etc/sudoers
user=user1
mkdir /home/$user/{.dev,.config,downloads,files,mnts}
chown -R $user /home/$user
chgrp -R wheel /home/$user

### SELF DELETE ###
printf '%s\n\n\n## INSTALLATION FINISHED ##\n  ## DELETING FILE IN ##\n\n'
printf '%s\t3..'
sleep 1
printf '%s2..'
sleep 1
printf '%s1..'
sleep 1
rm uefi-version
printf '%s\n\t  DONE\n'
