#!/bin/bash

sudo pacman -S xorg xfce4 xfce4-screenshooter xfce4-pulseaudio-plugin xfce4-netload-plugin lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings papirus-icon-theme arc-gtk-theme arc-icon-theme

sudo systemctl enable lightdm

## TO ADD: 
#pacman browser terminal
#maybe wire/nord/vm - need groups
#move files to appropriate location from folder
#make user directory (Downloads, Media, Documents etc..) not root made



