#!/bin/sh

# SETBG (file)
[ -f "$1" ] && cp "$1" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "WP changed" 

# SETBG (directory)
[ -d "$1" ] && cp "$(find "$1" -name "*.jpg"  -o -name "*.jpeg" -o -name "*.png" -type f | shuf -n 1)" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "WP changed"

# COMMAND
xwallpaper --zoom $HOME/.config/wall.png
